version: '3'
services:
  web:
    image: ellensu/nginxweb
    container_name: web
    ports:
     - "80:80"
    networks:
     - nginx
    environment:
     - NODE_ENV:"stg"
    restart: on-failure
networks:
  nginx:
    driver: bridge
